# Generated by Django 4.1 on 2023-01-04 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiajornalistica',
            name='data_atualizacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='materiajornalistica',
            name='status',
            field=models.CharField(choices=[('Publicado', 'Publicado'), ('Publicar em breve', 'Publicar em breve'), ('Guardado', 'Guardado'), ('Indefinido', 'Indefinido')], default='Indefinido', max_length=255),
        ),
        migrations.AlterField(
            model_name='materiajornalistica',
            name='id',
            field=models.CharField(default='37646942', max_length=255, primary_key=True, serialize=False),
        ),
    ]
