# Generated by Django 4.0.6 on 2022-08-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inserir_instancias_sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('observacao', models.TextField()),
            ],
        ),
    ]
