# Generated by Django 4.1.4 on 2023-01-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0002_materiajornalistica_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiajornalistica',
            name='id',
            field=models.CharField(default='1522873', max_length=255, primary_key=True, serialize=False),
        ),
    ]
