# Generated by Django 4.1 on 2022-11-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0002_inserir_instancias_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='definir_esforco_backlogitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esforco', models.CharField(choices=[('2', '2'), ('3', '3'), ('5', '5'), ('7', '7'), ('11', '11'), ('13', '13'), ('17', '17'), ('19', '19')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='definir_obs_backlogitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='definir_status_backlogitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('Item não foi resolvido', 'Não'), ('Item foi resolvido', 'Sim')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='inserir_instancias_dada_classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('observacao', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='inserir_instancias_sprint',
        ),
    ]
